Issue #110 - Added max attendee count as optional parameter for groups.
kir-dev/tanulo-next pull request #477
Opened 2020-10-12 22:15 UTC by vercibar

Closes #110

2020-10-12 23:15 UTC, triszt4n requested changes
All in all, nice implementation. 👍 ✨

2020-10-12 23:15 UTC, triszt4n commented on src/components/groups/group.middlewares.ts
> +    if (users.length > (req.body.maxAttendees || 100)) {
We do not have to query all the related users, we need the number of them, for which we could use:
```typescript
const userCount = await Group.relatedQuery('users').for(req.params.id).count()
```

This way, the query will be more goal-oriented and efficient.

2020-10-12 23:15 UTC, triszt4n commented on src/components/groups/group.middlewares.ts
> +    ((await Group.relatedQuery('users').for(req.group.id)).length < (group.maxAttendees || 100))) {
See other comment:
>  We do not have to query all the related users, we need the number of them, for which we could use:
> ```typescript
> const userCount = await Group.relatedQuery('users').for(req.params.id).count()
> ```
> 
> This way, the query will be more goal-oriented and efficient.

2020-10-12 23:15 UTC, triszt4n commented on migrations/20201012224257_add_max_attendees.ts
> +import * as Knex from "knex";
My eslint has been angry with the code:
![Screenshot 2020-10-13 01 05 10](https://user-images.githubusercontent.com/60111772/95798057-42111700-0cf1-11eb-967e-f2f980467721.png)

2020-10-13 08:22 UTC, OmTheTurtle requested changes
When dealing with default values, it's always safer to do it on database level. You can add a `.defaultTo(100)` to the migration, and with that you can remove the `|| 100` from the rest of the application.

2020-10-13 08:22 UTC, OmTheTurtle commented on src/components/groups/group.routes.ts
> +  isGroupOwnerOrAdmin, checkMaxAttendees
Let's move this to a new line.

2020-10-13 14:11 UTC, OmTheTurtle commented on views/group/show.pug
> +          .column.menu-label Résztvevők !{group.users.length} / !{group.maxAttendees || 100}
It's preferable to use the `#{variable}` syntax, as it escapes any potential text. Also, please remove the `|| 100` expressions here and in line 97 as they're not needed with the db-level default.

2020-10-15 18:37 UTC, OmTheTurtle commented
You have a file conflict with the latest changes on master, please rebase your branch and I'll approve.

2020-10-27 22:22 UTC, triszt4n approved these changes
Cool and good.

2020-10-31 14:03 UTC, OmTheTurtle approved these changes

2020-10-31 14:03 UTC, merged