Group improvements
kir-dev/tanulo-next pull request #751
Opened 2021-06-29 15:12 UTC by DannySS123

Users now can't join a group if it's already over, and instead of the join button there is a text saying that this group has expired.
 The "Kilépés" button's text color changed to black in light mode and to white in dark mode in order to match the others and for contrast improvements.
 Closes #741

2021-06-29 16:02 UTC, triszt4n requested changes
Nice. See request below. I'm thinking that maybe we should also inform the user if the group has already started. Maybe an "In session" label after the date in green font color (or after the Join button, but that wouldn't be very aesthetic).

2021-06-29 19:19 UTC, Tschonti commented
If you open a group page and then the group expires but you don't refresh, you can still join the group. This isn't big issue, but maybe there could be a check on the server side to make sure it's impossible to join an expired group, especially now that joining a group will send and email.

2021-06-30 10:04 UTC, OmTheTurtle commented on src/components/groups/group.middlewares.ts
> +    sendMessage(res, 'Ez a csoport már lejárt!')
I'd change the phrasing a little bit, what do you think of 'Ez a csoport már véget ért!'?

2021-06-30 10:05 UTC, OmTheTurtle commented on views/group/show.pug
> +      p(class="text-2xl text-red-700") Ez a csoport lejárt.
Same phrasing as above.

2021-07-04 17:06 UTC, OmTheTurtle approved these changes

2021-07-04 17:11 UTC, merged